# src/models/chat.py
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """
    Pydantic model for the incoming chat request.
    """
    question: str = Field(..., example="How many employees are in the Sales department?",
                          description="Natural language question to query the SQL database.")

class ChatResponse(BaseModel):
    """
    Pydantic model for the outgoing chat response.
    """
    answer: str = Field(..., example="There are 2 employees in the Sales department.",
                        description="The agent's natural language answer derived from the SQL query.")
    # You could add more fields here like 'sql_query' (for debugging/transparency), 'execution_time', etc.
    # sql_query: str = Field(None, description="The SQL query generated by the agent (for debugging).")